import type { DirectorProfessional } from './types'

/** Roster ATIVO gerado do AvecLake (salao_id=40613). */
export const BRASIL_DIRECTOR_PROFESSIONALS: DirectorProfessional[] = [
  { id: 'pro-brasil-ana-julia-sobral-de-souza', name: 'Ana Julia Sobral De Souza', avec_pro_id: '1072199', role: 'other', active: true },
  { id: 'pro-brasil-adrielle-rosa-dos-santos-pessanha', name: 'Adrielle Rosa Dos Santos Pessanha', avec_pro_id: '1114745', role: 'other', active: true },
  { id: 'pro-brasil-alan-fernando-de-albuquerque', name: 'Alan  Fernando De Albuquerque', avec_pro_id: '564703', role: 'hairstylist', active: true },
  { id: 'pro-brasil-alan-augusto-avec', name: 'Alan.augusto Avec', avec_pro_id: '917333', role: 'other', active: true },
  { id: 'pro-brasil-alberto-do-nascimento-tavares', name: 'Alberto Do Nascimento Tavares', avec_pro_id: '698351', role: 'other', active: true },
  { id: 'pro-brasil-alcides-alex-de-melo-almeida', name: 'Alcides Alex De Melo Almeida', avec_pro_id: '769745', role: 'other', active: true },
  { id: 'pro-brasil-alessandra-aparecida-ribeiro-assenco', name: 'Alessandra Aparecida Ribeiro Assenco', avec_pro_id: '1098748', role: 'other', active: true },
  { id: 'pro-brasil-aline-bispo-pereira', name: 'Aline Bispo Pereira', avec_pro_id: '1079032', role: 'other', active: true },
  { id: 'pro-brasil-aline-jabur', name: 'Aline Jabur', avec_pro_id: '925164', role: 'hairstylist', active: true },
  { id: 'pro-brasil-alison-alvarez', name: 'Alison Alvarez', avec_pro_id: '564702', role: 'hairstylist', active: true },
  { id: 'pro-brasil-alisson-de-souza-oliveira', name: 'Alisson De Souza Oliveira', avec_pro_id: '1005844', role: 'other', active: true },
  { id: 'pro-brasil-allan-vinicius-ortega', name: 'Allan Vinicius Ortega', avec_pro_id: '564705', role: 'hairstylist', active: true },
  { id: 'pro-brasil-almoxarifado', name: 'Almoxarifado', avec_pro_id: '995254', role: 'other', active: true },
  { id: 'pro-brasil-amanda-carolina-de-souza-marketing', name: 'Amanda Carolina De Souza (marketing)', avec_pro_id: '956757', role: 'other', active: true },
  { id: 'pro-brasil-amanda-equipe-dh', name: 'Amanda Equipe Dh', avec_pro_id: '1113311', role: 'other', active: true },
  { id: 'pro-brasil-amanda-martins-de-sousa', name: 'Amanda Martins De Sousa', avec_pro_id: '936479', role: 'other', active: true },
  { id: 'pro-brasil-amauri-baptista-bezerra', name: 'Amauri Baptista Bezerra', avec_pro_id: '848912', role: 'hairstylist', active: true },
  { id: 'pro-brasil-ana-luiza-calvacante-de-jesus', name: 'Ana Luiza Calvacante De Jesus', avec_pro_id: '955779', role: 'other', active: true },
  { id: 'pro-brasil-ana-paula-domene', name: 'Ana Paula Domene', avec_pro_id: '1005416', role: 'other', active: true },
  { id: 'pro-brasil-anderson-fonseca-oliveira', name: 'Anderson Fonseca Oliveira', avec_pro_id: '1036930', role: 'other', active: true },
  { id: 'pro-brasil-andrea-costa-cabral', name: 'Andrea Costa Cabral', avec_pro_id: '921293', role: 'other', active: true },
  { id: 'pro-brasil-andreia-da-silva-oliveira', name: 'Andreia Da Silva Oliveira', avec_pro_id: '564759', role: 'makeup', active: true },
  { id: 'pro-brasil-angela-cristina-de-souza-paiva', name: 'Angela Cristina De Souza Paiva', avec_pro_id: '922899', role: 'other', active: true },
  { id: 'pro-brasil-annakeylla', name: 'Annakeylla', avec_pro_id: '1115312', role: 'other', active: true },
  { id: 'pro-brasil-antonio-henrique-mariano-dos-reis', name: 'Antonio Henrique Mariano Dos Reis', avec_pro_id: '1114884', role: 'other', active: true },
  { id: 'pro-brasil-ariane-cristina-dos-santos', name: 'Ariane Cristina Dos Santos', avec_pro_id: '892361', role: 'other', active: true },
  { id: 'pro-brasil-auricaliane-da-silva-dantas', name: 'Auricaliane Da Silva Dantas', avec_pro_id: '698354', role: 'other', active: true },
  { id: 'pro-brasil-barbara-cabral-de-almeida', name: 'Barbara Cabral De Almeida', avec_pro_id: '1023390', role: 'other', active: true },
  { id: 'pro-brasil-barbara-duarte-sousa-silva', name: 'Barbara Duarte Sousa Silva', avec_pro_id: '999114', role: 'other', active: true },
  { id: 'pro-brasil-barbara-lins-junqueira-de-morais-alves', name: 'Barbara Lins Junqueira De Morais Alves', avec_pro_id: '1021983', role: 'other', active: true },
  { id: 'pro-brasil-baru-bistro-1', name: 'Baru Bistro 1', avec_pro_id: '574214', role: 'other', active: true },
  { id: 'pro-brasil-baru-bistro-2', name: 'Baru Bistro 2', avec_pro_id: '811346', role: 'other', active: true },
  { id: 'pro-brasil-baru-bistro-3', name: 'Baru Bistro 3', avec_pro_id: '811350', role: 'other', active: true },
  { id: 'pro-brasil-baru-bistro-4', name: 'Baru Bistro 4', avec_pro_id: '811352', role: 'other', active: true },
  { id: 'pro-brasil-baru-bistro-5', name: 'Baru Bistro 5', avec_pro_id: '811353', role: 'other', active: true },
  { id: 'pro-brasil-baru-bistro-6', name: 'Baru Bistro 6', avec_pro_id: '811354', role: 'other', active: true },
  { id: 'pro-brasil-beatriz-da-silva-santos', name: 'Beatriz Da Silva Santos', avec_pro_id: '564658', role: 'other', active: true },
  { id: 'pro-brasil-beatriz-praso', name: 'Beatriz Praso', avec_pro_id: '1111778', role: 'other', active: true },
  { id: 'pro-brasil-bianca-de-souza-mamed', name: 'Bianca De Souza Mamed', avec_pro_id: '1025417', role: 'other', active: true },
  { id: 'pro-brasil-bruna-da-silva-melo-domingues', name: 'Bruna Da Silva Melo Domingues', avec_pro_id: '1055182', role: 'hairstylist', active: true },
  { id: 'pro-brasil-bruna-de-souza-vieira', name: 'Bruna De Souza Vieira', avec_pro_id: '1101998', role: 'other', active: true },
  { id: 'pro-brasil-bruna-gomes-irineu', name: 'Bruna Gomes Irineu', avec_pro_id: '1061779', role: 'other', active: true },
  { id: 'pro-brasil-bruna-nunes-silva', name: 'Bruna Nunes Silva', avec_pro_id: '564709', role: 'other', active: true },
  { id: 'pro-brasil-brunna-fabricio', name: 'Brunna Fabricio', avec_pro_id: '564701', role: 'hairstylist', active: true },
  { id: 'pro-brasil-bruno-franca-de-souza', name: 'Bruno Franca De Souza', avec_pro_id: '936473', role: 'other', active: true },
  { id: 'pro-brasil-caio-alisson-biroli-de-oliveira', name: 'Caio Alisson Biroli De Oliveira', avec_pro_id: '1114886', role: 'other', active: true },
  { id: 'pro-brasil-camila-sartorato-burgarelli', name: 'Camila Sartorato Burgarelli', avec_pro_id: '564712', role: 'hairstylist', active: true },
  { id: 'pro-brasil-camylla-rodrigues-ferreira', name: 'Camylla Rodrigues Ferreira', avec_pro_id: '983966', role: 'other', active: true },
  { id: 'pro-brasil-canon-carvalho-de-paula', name: 'Canon Carvalho De Paula', avec_pro_id: '1000789', role: 'hairstylist', active: true },
  { id: 'pro-brasil-carey-dos-santos-castro', name: 'Carey Dos Santos Castro', avec_pro_id: '911291', role: 'other', active: true },
  { id: 'pro-brasil-carine-santana-sales', name: 'Carine Santana Sales', avec_pro_id: '759610', role: 'other', active: true },
  { id: 'pro-brasil-carlos-henrique-oliveira-gomes-de-sampaio', name: 'Carlos Henrique Oliveira Gomes De Sampaio', avec_pro_id: '1044548', role: 'other', active: true },
  { id: 'pro-brasil-carlos-vinicius-borges', name: 'Carlos Vinicius Borges', avec_pro_id: '897433', role: 'other', active: true },
  { id: 'pro-brasil-cassia-queiroz-equipe-dh', name: 'Cassia Queiroz Equipe Dh', avec_pro_id: '1112723', role: 'other', active: true },
  { id: 'pro-brasil-catharina-de-souza-moraes-bello', name: 'Catharina De Souza Moraes Bello', avec_pro_id: '1082437', role: 'other', active: true },
  { id: 'pro-brasil-celso-marcos-de-lima-neto', name: 'Celso Marcos De Lima Neto', avec_pro_id: '1114912', role: 'other', active: true },
  { id: 'pro-brasil-cesar-augusto-jose-silva', name: 'Cesar Augusto Jose Silva', avec_pro_id: '1110673', role: 'other', active: true },
  { id: 'pro-brasil-claudiana-bezerra-da-silva', name: 'Claudiana Bezerra Da Silva', avec_pro_id: '841088', role: 'hairstylist', active: true },
  { id: 'pro-brasil-claudionor-almeida-de-souza', name: 'Claudionor Almeida De Souza', avec_pro_id: '921351', role: 'other', active: true },
  { id: 'pro-brasil-cleitiana-almeida-de-arruda', name: 'Cleitiana Almeida De Arruda', avec_pro_id: '1011779', role: 'other', active: true },
  { id: 'pro-brasil-contabil', name: 'Contabil', avec_pro_id: '596523', role: 'other', active: true },
  { id: 'pro-brasil-daniel-viana-martins', name: 'Daniel Viana Martins', avec_pro_id: '881747', role: 'hairstylist', active: true },
  { id: 'pro-brasil-daniela-conceicao-de-amorim', name: 'Daniela Conceição De Amorim', avec_pro_id: '1094553', role: 'other', active: true },
  { id: 'pro-brasil-daniela-mariniello', name: 'Daniela Mariniello', avec_pro_id: '564700', role: 'hairstylist', active: true },
  { id: 'pro-brasil-danilo-hebert', name: 'Danilo Hebert', avec_pro_id: '1112707', role: 'hairstylist', active: true },
  { id: 'pro-brasil-darcy-mitiko-cavalheiro', name: 'Darcy Mitiko Cavalheiro', avec_pro_id: '1063612', role: 'hairstylist', active: true },
  { id: 'pro-brasil-david-barbosa-da-silva', name: 'David Barbosa Da Silva', avec_pro_id: '863358', role: 'other', active: true },
  { id: 'pro-brasil-dayana-marques-silva-pinto', name: 'Dayana Marques Silva Pinto', avec_pro_id: '713737', role: 'hairstylist', active: true },
  { id: 'pro-brasil-debora-souza-guimaraes', name: 'Debora Souza Guimaraes', avec_pro_id: '1115819', role: 'other', active: true },
  { id: 'pro-brasil-debora-viegas-savie', name: 'Debora Viegas (savie)', avec_pro_id: '995047', role: 'other', active: true },
  { id: 'pro-brasil-depilacao-3', name: 'Depilacao - 3', avec_pro_id: '856469', role: 'other', active: true },
  { id: 'pro-brasil-diego-equipe-dh', name: 'Diego Equipe Dh', avec_pro_id: '1112716', role: 'other', active: true },
  { id: 'pro-brasil-diego-marcorio-santana', name: 'Diego Marcorio Santana', avec_pro_id: '1017350', role: 'hairstylist', active: true },
  { id: 'pro-brasil-diogo-marcelo-pitaro', name: 'Diogo Marcelo Pitaro', avec_pro_id: '564698', role: 'hairstylist', active: true },
  { id: 'pro-brasil-dona-carmen-e-jacque-joias', name: 'Dona Carmen E Jacque (jóias)', avec_pro_id: '995045', role: 'other', active: true },
  { id: 'pro-brasil-douglas-da-conceicao-garcia', name: 'Douglas Da Conceição Garcia', avec_pro_id: '564697', role: 'hairstylist', active: true },
  { id: 'pro-brasil-douglas-de-oliveira-lima', name: 'Douglas De Oliveira Lima', avec_pro_id: '948961', role: 'other', active: true },
  { id: 'pro-brasil-edijane-maria-de-macedo', name: 'Edijane Maria De Macedo', avec_pro_id: '873172', role: 'other', active: true },
  { id: 'pro-brasil-edilandia-costa-de-almeida', name: 'Edilandia Costa De Almeida', avec_pro_id: '952245', role: 'other', active: true },
  { id: 'pro-brasil-elaine-moraes', name: 'Elaine Moraes', avec_pro_id: '530884', role: 'other', active: true },
  { id: 'pro-brasil-eliane-almeida-dos-santos', name: 'Eliane Almeida Dos Santos', avec_pro_id: '915472', role: 'other', active: true },
  { id: 'pro-brasil-eliane-ferreira-costa', name: 'Eliane Ferreira Costa', avec_pro_id: '896193', role: 'hairstylist', active: true },
  { id: 'pro-brasil-elisa-mara-rocha', name: 'Elisa Mara Rocha', avec_pro_id: '1107998', role: 'other', active: true },
  { id: 'pro-brasil-elisangela-rocha-santos', name: 'Elisangela Rocha Santos', avec_pro_id: '1114909', role: 'other', active: true },
  { id: 'pro-brasil-eliseu-vicente-da-conceicao', name: 'Eliseu Vicente Da Conceicao', avec_pro_id: '629065', role: 'other', active: true },
  { id: 'pro-brasil-ellen-dos-santos-silva', name: 'Ellen Dos Santos Silva', avec_pro_id: '997576', role: 'other', active: true },
  { id: 'pro-brasil-elvis-teixeira-dos-santos', name: 'Elvis Teixeira Dos Santos', avec_pro_id: '926194', role: 'hairstylist', active: true },
  { id: 'pro-brasil-emanuel-antonio-modena', name: 'Emanuel Antonio Modena', avec_pro_id: '564717', role: 'hairstylist', active: true },
  { id: 'pro-brasil-eni-jose-chiavagatti', name: 'Eni Jose Chiavagatti', avec_pro_id: '881173', role: 'other', active: true },
  { id: 'pro-brasil-erculy-silva-dos-santos', name: 'Erculy Silva Dos Santos', avec_pro_id: '1101982', role: 'other', active: true },
  { id: 'pro-brasil-erick-henrique-ferrreira-silva', name: 'Erick Henrique Ferrreira Silva', avec_pro_id: '1012841', role: 'other', active: true },
  { id: 'pro-brasil-erika-evangelista-andrade-de-santana', name: 'Erika Evangelista Andrade De Santana', avec_pro_id: '1083319', role: 'other', active: true },
  { id: 'pro-brasil-erismar-ferreira-da-silva', name: 'Erismar Ferreira Da Silva', avec_pro_id: '757099', role: 'other', active: true },
  { id: 'pro-brasil-ers-contabilidade', name: 'Ers Contabilidade', avec_pro_id: '1114291', role: 'other', active: true },
  { id: 'pro-brasil-estela-souza-dias', name: 'Estela Souza Dias', avec_pro_id: '919875', role: 'other', active: true },
  { id: 'pro-brasil-evandro-mikel-equipe-dh', name: 'Evandro Mikel Equipe Dh', avec_pro_id: '1112719', role: 'other', active: true },
  { id: 'pro-brasil-eveline-rodrigues-da-silva', name: 'Eveline Rodrigues Da Silva', avec_pro_id: '915468', role: 'other', active: true },
  { id: 'pro-brasil-everton-sousa-da-silva', name: 'Everton Sousa Da Silva', avec_pro_id: '941360', role: 'other', active: true },
  { id: 'pro-brasil-fabiane-rezende-simoes', name: 'Fabiane Rezende Simões', avec_pro_id: '1117852', role: 'other', active: true },
  { id: 'pro-brasil-felipe-batista-de-oliveira', name: 'Felipe Batista De Oliveira', avec_pro_id: '725564', role: 'other', active: true },
  { id: 'pro-brasil-fernanda-da-cruz-araujo', name: 'Fernanda Da Cruz Araujo', avec_pro_id: '711373', role: 'other', active: true },
  { id: 'pro-brasil-fernanda-faria-equipe-dh', name: 'Fernanda Faria Equipe Dh', avec_pro_id: '1112712', role: 'other', active: true },
  { id: 'pro-brasil-fernanda-magalhaes-araujo', name: 'Fernanda Magalhães Araujo', avec_pro_id: '1090359', role: 'other', active: true },
  { id: 'pro-brasil-fernando-cesar-nascimento-de-jesus', name: 'Fernando Cesar Nascimento De Jesus', avec_pro_id: '1101984', role: 'other', active: true },
  { id: 'pro-brasil-fernando-nantes-romero', name: 'Fernando Nantes Romero', avec_pro_id: '1070250', role: 'hairstylist', active: true },
  { id: 'pro-brasil-flavia-silva-dos-santos', name: 'Flavia Silva Dos Santos', avec_pro_id: '1101987', role: 'other', active: true },
  { id: 'pro-brasil-flavio-barreto-barbosa', name: 'Flavio Barreto Barbosa', avec_pro_id: '1085805', role: 'other', active: true },
  { id: 'pro-brasil-francisca-meireles-do-nascimento', name: 'Francisca Meireles Do Nascimento', avec_pro_id: '853823', role: 'other', active: true },
  { id: 'pro-brasil-gabriel-correia-de-loiola', name: 'Gabriel Correia De Loiola', avec_pro_id: '1014216', role: 'other', active: true },
  { id: 'pro-brasil-gabriel-crisostomo-couto-de-almeida-fotografo', name: 'Gabriel Crisostomo Couto De Almeida (fotografo)', avec_pro_id: '1014489', role: 'other', active: true },
  { id: 'pro-brasil-gabriel-de-sa-costa', name: 'Gabriel De Sa Costa', avec_pro_id: '1012668', role: 'other', active: true },
  { id: 'pro-brasil-gabriel-fantin-viana', name: 'Gabriel Fantin Viana', avec_pro_id: '954935', role: 'other', active: true },
  { id: 'pro-brasil-gabriel-gaifem-leite-schueler', name: 'Gabriel Gaifem Leite Schueler', avec_pro_id: '1065614', role: 'other', active: true },
  { id: 'pro-brasil-gabriel-john-dos-santos', name: 'Gabriel John Dos Santos', avec_pro_id: '564723', role: 'hairstylist', active: true },
  { id: 'pro-brasil-gabriela-santos', name: 'Gabriela  Santos', avec_pro_id: '818098', role: 'other', active: true },
  { id: 'pro-brasil-gabrielle-queiroz-nascimento', name: 'Gabrielle Queiroz Nascimento', avec_pro_id: '889915', role: 'other', active: true },
  { id: 'pro-brasil-gabrielly-cristina-de-almeida-santos', name: 'Gabrielly Cristina De Almeida Santos', avec_pro_id: '1000839', role: 'other', active: true },
  { id: 'pro-brasil-geovane-dos-prazeres-lopes', name: 'Geovane Dos Prazeres Lopes', avec_pro_id: '1057227', role: 'makeup', active: true },
  { id: 'pro-brasil-geovanna-cavalcanti-da-silva', name: 'Geovanna Cavalcanti Da Silva', avec_pro_id: '1067687', role: 'other', active: true },
  { id: 'pro-brasil-geyda-rayana-pinheiro-de-sousa', name: 'Geyda Rayana Pinheiro De Sousa', avec_pro_id: '693653', role: 'other', active: true },
  { id: 'pro-brasil-geyza-melo-de-araujo', name: 'Geyza Melo De Araujo', avec_pro_id: '762708', role: 'hairstylist', active: true },
  { id: 'pro-brasil-ghabryel-flores-martins', name: 'Ghabryel Flores Martins', avec_pro_id: '1119172', role: 'hairstylist', active: true },
  { id: 'pro-brasil-giovanna-silva-oliveira', name: 'Giovanna Silva Oliveira', avec_pro_id: '955777', role: 'other', active: true },
  { id: 'pro-brasil-girlane-silva-santana', name: 'Girlane Silva Santana', avec_pro_id: '1110302', role: 'other', active: true },
  { id: 'pro-brasil-gisele-costa-dos-santos', name: 'Gisele Costa Dos Santos', avec_pro_id: '849385', role: 'other', active: true },
  { id: 'pro-brasil-gloria-maria-dos-santos', name: 'Gloria Maria Dos Santos', avec_pro_id: '1099860', role: 'other', active: true },
  { id: 'pro-brasil-grazielly-lima-dos-santos', name: 'Grazielly Lima Dos Santos', avec_pro_id: '921621', role: 'other', active: true },
  { id: 'pro-brasil-guilherme-bortoto-ferreira', name: 'Guilherme Bortoto Ferreira', avec_pro_id: '957725', role: 'other', active: true },
  { id: 'pro-brasil-guilherme-machado-silva', name: 'Guilherme Machado Silva', avec_pro_id: '564727', role: 'hairstylist', active: true },
  { id: 'pro-brasil-gustavo-colonno', name: 'Gustavo Colonno', avec_pro_id: '749213', role: 'hairstylist', active: true },
  { id: 'pro-brasil-gustavo-da-silva-melo', name: 'Gustavo Da Silva Melo', avec_pro_id: '1057942', role: 'other', active: true },
  { id: 'pro-brasil-gustavo-fontes-de-o', name: 'Gustavo Fontes De O', avec_pro_id: '885156', role: 'hairstylist', active: true },
  { id: 'pro-brasil-gustavo-hessel-soares-de-macedo', name: 'Gustavo Hessel Soares De Macedo', avec_pro_id: '1102004', role: 'other', active: true },
  { id: 'pro-brasil-hanely-nadine-de-lima-miranda', name: 'Hanely Nadine De Lima Miranda', avec_pro_id: '1117743', role: 'other', active: true },
  { id: 'pro-brasil-henrique-tenorio-da-silva', name: 'Henrique Tenório Da Silva', avec_pro_id: '1027872', role: 'hairstylist', active: true },
  { id: 'pro-brasil-ingrid-rani-da-silva', name: 'Ingrid Rani Da Silva', avec_pro_id: '1012665', role: 'other', active: true },
  { id: 'pro-brasil-ingrid-silva-barreto', name: 'Ingrid Silva Barreto', avec_pro_id: '883568', role: 'other', active: true },
  { id: 'pro-brasil-isabela-ramalho-da-silva', name: 'Isabela Ramalho Da Silva', avec_pro_id: '995024', role: 'other', active: true },
  { id: 'pro-brasil-isabela-rodrigues-chaves-spinola', name: 'Isabela Rodrigues Chaves Spinola', avec_pro_id: '931764', role: 'other', active: true },
  { id: 'pro-brasil-isabella-acioli-nato-da-silva', name: 'Isabella Acioli Nato Da Silva', avec_pro_id: '917848', role: 'other', active: true },
  { id: 'pro-brasil-isabella-de-paula-santos', name: 'Isabella De Paula Santos', avec_pro_id: '1037072', role: 'other', active: true },
  { id: 'pro-brasil-isla-paola-felizarda-oliveira-brandao', name: 'Isla Paola Felizarda Oliveira Brandao', avec_pro_id: '1076145', role: 'other', active: true },
  { id: 'pro-brasil-islayquiel-rodrigues-de-sena', name: 'Islayquiel Rodrigues De Sena', avec_pro_id: '992741', role: 'other', active: true },
  { id: 'pro-brasil-jacinta-maciel-da-silva', name: 'Jacinta Maciel Da Silva', avec_pro_id: '962435', role: 'other', active: true },
  { id: 'pro-brasil-jacqueline-alves-da-silva', name: 'Jacqueline Alves Da Silva', avec_pro_id: '1101711', role: 'other', active: true },
  { id: 'pro-brasil-jailton-derlei-de-oliveira', name: 'Jailton Derlei De Oliveira', avec_pro_id: '996180', role: 'other', active: true },
  { id: 'pro-brasil-janaina-santana', name: 'Janaina Santana', avec_pro_id: '574198', role: 'hairstylist', active: true },
  { id: 'pro-brasil-janderson-de-sa-barros', name: 'Janderson De Sa Barros', avec_pro_id: '944910', role: 'hairstylist', active: true },
  { id: 'pro-brasil-jaqueline-fernandes-de-melo', name: 'Jaqueline Fernandes De Melo', avec_pro_id: '915792', role: 'other', active: true },
  { id: 'pro-brasil-jaqueline-ribeiro-dos-santos', name: 'Jaqueline Ribeiro Dos Santos', avec_pro_id: '564729', role: 'other', active: true },
  { id: 'pro-brasil-jayne-da-cruz-nobre', name: 'Jayne Da Cruz Nobre', avec_pro_id: '578542', role: 'other', active: true },
  { id: 'pro-brasil-jefferson-policarpo-dos-santos', name: 'Jefferson Policarpo Dos Santos', avec_pro_id: '901877', role: 'other', active: true },
  { id: 'pro-brasil-jessica-sampaio-querino', name: 'Jessica Sampaio Querino', avec_pro_id: '564730', role: 'other', active: true },
  { id: 'pro-brasil-jessica-silva-freitas', name: 'Jessica Silva Freitas', avec_pro_id: '1109077', role: 'other', active: true },
  { id: 'pro-brasil-jhennyfer-lima-equipe-dh', name: 'Jhennyfer Lima Equipe Dh', avec_pro_id: '1113309', role: 'other', active: true },
  { id: 'pro-brasil-joao-felipe-candido-marketing', name: 'Joao Felipe Candido (marketing)', avec_pro_id: '1011432', role: 'other', active: true },
  { id: 'pro-brasil-joao-vitor-godarth-fernandes', name: 'Joao Vitor Godarth Fernandes', avec_pro_id: '1109093', role: 'other', active: true },
  { id: 'pro-brasil-johnatan-de-souza-santana', name: 'Johnatan De Souza Santana', avec_pro_id: '859586', role: 'other', active: true },
  { id: 'pro-brasil-johnny-augusto-perez-correa', name: 'Johnny Augusto Perez Correa', avec_pro_id: '982873', role: 'other', active: true },
  { id: 'pro-brasil-jonathan-dias-dos-santos', name: 'Jonathan Dias Dos Santos', avec_pro_id: '564664', role: 'other', active: true },
  { id: 'pro-brasil-jose-antonio-dias-de-carvalho', name: 'Jose Antonio Dias De Carvalho', avec_pro_id: '564733', role: 'other', active: true },
  { id: 'pro-brasil-jose-virgilio-mendes', name: 'Jose Virgilio Mendes', avec_pro_id: '1117745', role: 'other', active: true },
  { id: 'pro-brasil-josenildo-de-oliveira', name: 'Josenildo De Oliveira', avec_pro_id: '920722', role: 'hairstylist', active: true },
  { id: 'pro-brasil-joao-pedro-bento-de-oliveira', name: 'João Pedro Bento De Oliveira', avec_pro_id: '1102007', role: 'other', active: true },
  { id: 'pro-brasil-juan-dos-santos-silva', name: 'Juan Dos Santos Silva', avec_pro_id: '720905', role: 'other', active: true },
  { id: 'pro-brasil-julia-alves-goncalves', name: 'Julia Alves Gonçalves', avec_pro_id: '1074901', role: 'other', active: true },
  { id: 'pro-brasil-juliana-braga', name: 'Juliana Braga', avec_pro_id: '1057795', role: 'other', active: true },
  { id: 'pro-brasil-juliana-lucki', name: 'Juliana Lucki', avec_pro_id: '1045381', role: 'other', active: true },
  { id: 'pro-brasil-juliana-souza-rosa-da-silva', name: 'Juliana Souza Rosa Da Silva', avec_pro_id: '922263', role: 'other', active: true },
  { id: 'pro-brasil-juliano-sousa-lemos', name: 'Juliano Sousa Lemos', avec_pro_id: '859867', role: 'hairstylist', active: true },
  { id: 'pro-brasil-jussara-vitoria-santos-frade', name: 'Jussara Vitoria Santos Frade', avec_pro_id: '1121678', role: 'other', active: true },
  { id: 'pro-brasil-kaique-dos-santos-souza', name: 'Kaique Dos Santos Souza', avec_pro_id: '656473', role: 'other', active: true },
  { id: 'pro-brasil-kamila-barros-lima-da-silva', name: 'Kamila Barros Lima Da Silva', avec_pro_id: '778293', role: 'other', active: true },
  { id: 'pro-brasil-karin-ferreira-de-lima-silva', name: 'Karin Ferreira De Lima Silva', avec_pro_id: '564737', role: 'other', active: true },
  { id: 'pro-brasil-karina-marques', name: 'Karina Marques', avec_pro_id: '778527', role: 'other', active: true },
  { id: 'pro-brasil-kateryne-dos-santos-paim', name: 'Kateryne Dos Santos Paim', avec_pro_id: '1072171', role: 'other', active: true },
  { id: 'pro-brasil-katia-aparecida-dos-santos-silva', name: 'Katia Aparecida Dos Santos Silva', avec_pro_id: '1021906', role: 'other', active: true },
  { id: 'pro-brasil-kaue-ryan-da-silva', name: 'Kauê Ryan Da Silva', avec_pro_id: '1011346', role: 'other', active: true },
  { id: 'pro-brasil-laudenilva-dos-santos-silva', name: 'Laudenilva Dos Santos Silva', avec_pro_id: '1033628', role: 'hairstylist', active: true },
  { id: 'pro-brasil-layra-pereira-equipe-dh', name: 'Layra Pereira Equipe Dh', avec_pro_id: '1112722', role: 'other', active: true },
  { id: 'pro-brasil-leandro-santos-marques', name: 'Leandro Santos Marques', avec_pro_id: '847694', role: 'other', active: true },
  { id: 'pro-brasil-leiane-correia-avila', name: 'Leiane Correia Ávila', avec_pro_id: '830327', role: 'hairstylist', active: true },
  { id: 'pro-brasil-leonardo-a-tomaz', name: 'Leonardo A. Tomaz', avec_pro_id: '1062498', role: 'hairstylist', active: true },
  { id: 'pro-brasil-leonel-claret-borges-bernardo', name: 'Leonel Claret Borges Bernardo', avec_pro_id: '564690', role: 'hairstylist', active: true },
  { id: 'pro-brasil-leticia-dantas-oliveira', name: 'Leticia Dantas Oliveira', avec_pro_id: '567789', role: 'other', active: true },
  { id: 'pro-brasil-leticia-faeiro-de-jesus', name: 'Letícia Faeiro De Jesus', avec_pro_id: '1113114', role: 'other', active: true },
  { id: 'pro-brasil-lista-de-espera', name: 'Lista De Espera', avec_pro_id: '897191', role: 'other', active: true },
  { id: 'pro-brasil-lizandra-jacinto-mota', name: 'Lizandra Jacinto Mota', avec_pro_id: '915470', role: 'other', active: true },
  { id: 'pro-brasil-luan-aniello-franca-porreca-utiyama', name: 'Luan Aniello França Porreca Utiyama', avec_pro_id: '1065624', role: 'other', active: true },
  { id: 'pro-brasil-luana-conceicao-dos-santos', name: 'Luana Conceicao Dos Santos', avec_pro_id: '914915', role: 'other', active: true },
  { id: 'pro-brasil-luana-larissa-pinheiro-de-sousa', name: 'Luana Larissa Pinheiro De Sousa', avec_pro_id: '723184', role: 'other', active: true },
  { id: 'pro-brasil-luana-silva-dos-santos', name: 'Luana Silva Dos Santos', avec_pro_id: '1102010', role: 'other', active: true },
  { id: 'pro-brasil-lucas-campos-de-macedo', name: 'Lucas Campos De Macedo', avec_pro_id: '564688', role: 'hairstylist', active: true },
  { id: 'pro-brasil-lucas-gustavo-de-sales-e-sales', name: 'Lucas Gustavo De Sales E Sales', avec_pro_id: '913492', role: 'hairstylist', active: true },
  { id: 'pro-brasil-lucas-rodrigues', name: 'Lucas Rodrigues', avec_pro_id: '564665', role: 'other', active: true },
  { id: 'pro-brasil-lucimar-aparecida-de-carvalho', name: 'Lucimar Aparecida De Carvalho', avec_pro_id: '1080662', role: 'other', active: true },
  { id: 'pro-brasil-lucimary-cossenzo', name: 'Lucimary Cossenzo', avec_pro_id: '564689', role: 'hairstylist', active: true },
  { id: 'pro-brasil-luiz-gustavo-lins-da-silva', name: 'Luiz Gustavo Lins Da Silva', avec_pro_id: '1022632', role: 'other', active: true },
  { id: 'pro-brasil-luiza-antonia-amaro-pinto', name: 'Luiza Antonia Amaro Pinto', avec_pro_id: '713137', role: 'makeup', active: true },
  { id: 'pro-brasil-lukas-mendes-oliveira-santos', name: 'Lukas Mendes Oliveira Santos', avec_pro_id: '1097254', role: 'other', active: true },
  { id: 'pro-brasil-luziene-suely-mateus', name: 'Luziene Suely Mateus', avec_pro_id: '887915', role: 'other', active: true },
  { id: 'pro-brasil-manoel-sergio-goncalves', name: 'Manoel Sergio Gonçalves', avec_pro_id: '564686', role: 'hairstylist', active: true },
  { id: 'pro-brasil-maraisa-pamela-figueiredo', name: 'Maraisa Pamela Figueiredo', avec_pro_id: '660834', role: 'other', active: true },
  { id: 'pro-brasil-marcela-oliveira-santos', name: 'Marcela Oliveira Santos', avec_pro_id: '1075961', role: 'other', active: true },
  { id: 'pro-brasil-marcella-de-araujo-garcia', name: 'Marcella De Araujo Garcia', avec_pro_id: '698353', role: 'other', active: true },
  { id: 'pro-brasil-marcelo-ferreira-rocha', name: 'Marcelo Ferreira Rocha', avec_pro_id: '1102014', role: 'other', active: true },
  { id: 'pro-brasil-marcelo-harpa', name: 'Marcelo Harpa', avec_pro_id: '848433', role: 'hairstylist', active: true },
  { id: 'pro-brasil-marcelo-sabino-luis-junior', name: 'Marcelo Sabino Luis Junior', avec_pro_id: '776121', role: 'other', active: true },
  { id: 'pro-brasil-marciel-dantas-de-brito', name: 'Marciel Dantas De Brito', avec_pro_id: '718394', role: 'other', active: true },
  { id: 'pro-brasil-marco-aurelio-oliveira-carneiro', name: 'Marco Aurelio Oliveira Carneiro', avec_pro_id: '933339', role: 'other', active: true },
  { id: 'pro-brasil-marcos-henrique-da-silva-bonfim', name: 'Marcos Henrique Da Silva Bonfim', avec_pro_id: '1015817', role: 'other', active: true },
  { id: 'pro-brasil-marcos-karlovic-junior-cabeleireiro', name: 'Marcos Karlovic Junior Cabeleireiro', avec_pro_id: '920126', role: 'hairstylist', active: true },
  { id: 'pro-brasil-marcos-paulo-alves-soares', name: 'Marcos Paulo Alves Soares', avec_pro_id: '1104081', role: 'other', active: true },
  { id: 'pro-brasil-maria-ana-da-silva-souza', name: 'Maria Ana Da Silva Souza', avec_pro_id: '921957', role: 'hairstylist', active: true },
  { id: 'pro-brasil-maria-carolina-pijamas', name: 'Maria Carolina (pijamas)', avec_pro_id: '995018', role: 'other', active: true },
  { id: 'pro-brasil-maria-da-conceicao-pereira-dias', name: 'Maria Da Conceição Pereira Dias', avec_pro_id: '566202', role: 'other', active: true },
  { id: 'pro-brasil-maria-das-dores-de-souza', name: 'Maria Das Dores De Souza', avec_pro_id: '1054409', role: 'other', active: true },
  { id: 'pro-brasil-maria-eduarda-teixeira-do-amaral', name: 'Maria Eduarda Teixeira Do Amaral', avec_pro_id: '1057210', role: 'other', active: true },
  { id: 'pro-brasil-maria-eliana-neres-de-moura', name: 'Maria Eliana Neres De Moura', avec_pro_id: '564768', role: 'other', active: true },
  { id: 'pro-brasil-maria-ines-almeida-guedes-da-silva', name: 'Maria Ines Almeida Guedes Da Silva', avec_pro_id: '925903', role: 'other', active: true },
  { id: 'pro-brasil-maria-jilvania-pereira-de-santana', name: 'Maria Jilvania Pereira De Santana', avec_pro_id: '1022824', role: 'other', active: true },
  { id: 'pro-brasil-maria-lucia-dos-santos', name: 'Maria Lucia Dos Santos', avec_pro_id: '1081208', role: 'other', active: true },
  { id: 'pro-brasil-maria-luiza-brito-silva-carvalho', name: 'Maria Luiza Brito Silva Carvalho', avec_pro_id: '564684', role: 'hairstylist', active: true },
  { id: 'pro-brasil-maria-samila-nascimento-dos-santos', name: 'Maria Samila Nascimento Dos Santos', avec_pro_id: '766980', role: 'other', active: true },
  { id: 'pro-brasil-maria-tereza-luis-de-paiva', name: 'Maria Tereza Luis De Paiva', avec_pro_id: '920721', role: 'hairstylist', active: true },
  { id: 'pro-brasil-maria-valquiria-diogo', name: 'Maria Valquiria Diogo', avec_pro_id: '915791', role: 'other', active: true },
  { id: 'pro-brasil-mariana-mendes-thomas', name: 'Mariana Mendes Thomas', avec_pro_id: '977851', role: 'other', active: true },
  { id: 'pro-brasil-marilia-gabriela-martins', name: 'Marilia Gabriela Martins', avec_pro_id: '924626', role: 'hairstylist', active: true },
  { id: 'pro-brasil-marina-alves-da-silva', name: 'Marina Alves Da Silva', avec_pro_id: '1005533', role: 'other', active: true },
  { id: 'pro-brasil-marina-mattar-mantelatto', name: 'Marina Mattar Mantelatto', avec_pro_id: '564761', role: 'makeup', active: true },
  { id: 'pro-brasil-marjorie-maciel-joias', name: 'Marjorie Maciel (jóias)', avec_pro_id: '995017', role: 'other', active: true },
  { id: 'pro-brasil-marjory-silva', name: 'Marjory Silva', avec_pro_id: '947091', role: 'hairstylist', active: true },
  { id: 'pro-brasil-marya-victtoria-pessoa-veiga', name: 'Marya Victtoria Pessoa Veiga', avec_pro_id: '972142', role: 'other', active: true },
  { id: 'pro-brasil-massagem-5', name: 'Massagem 5', avec_pro_id: '789336', role: 'other', active: true },
  { id: 'pro-brasil-mauri-lima', name: 'Mauri Lima', avec_pro_id: '1056217', role: 'hairstylist', active: true },
  { id: 'pro-brasil-mauricio-de-carvalho-lima', name: 'Mauricio De Carvalho Lima', avec_pro_id: '564683', role: 'hairstylist', active: true },
  { id: 'pro-brasil-mayara-muniz-pereira', name: 'Mayara Muniz Pereira', avec_pro_id: '564744', role: 'other', active: true },
  { id: 'pro-brasil-mayara-neves-de-sousa-ribeiro', name: 'Mayara Neves De Sousa Ribeiro', avec_pro_id: '1004511', role: 'other', active: true },
  { id: 'pro-brasil-maykon-luiz-dos-santos-cardozo', name: 'Maykon Luiz Dos Santos Cardozo', avec_pro_id: '885146', role: 'hairstylist', active: true },
  { id: 'pro-brasil-melissa-schelotag-de-moraes', name: 'Melissa Schelotag De Moraes', avec_pro_id: '1100542', role: 'other', active: true },
  { id: 'pro-brasil-michele-florentino-botelho', name: 'Michele Florentino Botelho', avec_pro_id: '783398', role: 'other', active: true },
  { id: 'pro-brasil-midia-de-jesus-ferreira', name: 'Midiã De Jesus Ferreira', avec_pro_id: '564769', role: 'other', active: true },
  { id: 'pro-brasil-miguel-natan-souza-dos-santos', name: 'Miguel Natan Souza Dos Santos', avec_pro_id: '1121770', role: 'other', active: true },
  { id: 'pro-brasil-milena-agnes-correa-e-silva', name: 'Milena Agnes Correa E Silva', avec_pro_id: '1102642', role: 'other', active: true },
  { id: 'pro-brasil-millena-costa-santos-da-cruz', name: 'Millena Costa Santos Da Cruz', avec_pro_id: '955790', role: 'other', active: true },
  { id: 'pro-brasil-milly-maia-bezerra', name: 'Milly Maia Bezerra', avec_pro_id: '966261', role: 'other', active: true },
  { id: 'pro-brasil-miqueias-salvador-de-oliveira', name: 'Miqueias Salvador De Oliveira', avec_pro_id: '1104146', role: 'hairstylist', active: true },
  { id: 'pro-brasil-miriele-santos-carneiro', name: 'Miriele Santos Carneiro', avec_pro_id: '1104891', role: 'other', active: true },
  { id: 'pro-brasil-moises-de-oliveira-felicio', name: 'Moises De Oliveira Felicio', avec_pro_id: '1117746', role: 'other', active: true },
  { id: 'pro-brasil-monique-borella-couto', name: 'Monique Borella Couto', avec_pro_id: '564762', role: 'makeup', active: true },
  { id: 'pro-brasil-monique-lia-buna-castro-dos-santos', name: 'Monique Lia Buna Castro Dos Santos', avec_pro_id: '564682', role: 'hairstylist', active: true },
  { id: 'pro-brasil-nanda-gomes', name: 'Nanda Gomes', avec_pro_id: '564694', role: 'hairstylist', active: true },
  { id: 'pro-brasil-narcelho-alves-santos', name: 'Narcelho Alves Santos', avec_pro_id: '913956', role: 'hairstylist', active: true },
  { id: 'pro-brasil-natalie-lima-dona-pijamas', name: 'Natalie Lima (dona Pijamas)', avec_pro_id: '995052', role: 'other', active: true },
  { id: 'pro-brasil-nataly-cristina-da-silva-savie', name: 'Nataly Cristina Da Silva (savie)', avec_pro_id: '995014', role: 'other', active: true },
  { id: 'pro-brasil-natan-pereira-de-araujo-gomes', name: 'Natan Pereira De Araujo Gomes', avec_pro_id: '989848', role: 'other', active: true },
  { id: 'pro-brasil-nathalia-muccio', name: 'Nathalia Muccio', avec_pro_id: '1022926', role: 'other', active: true },
  { id: 'pro-brasil-nathalia-sartorato-burgarelli', name: 'Nathalia Sartorato Burgarelli', avec_pro_id: '569496', role: 'other', active: true },
  { id: 'pro-brasil-nathan-elias-magalhaes-lima', name: 'Nathan Elias Magalhães Lima', avec_pro_id: '918633', role: 'hairstylist', active: true },
  { id: 'pro-brasil-nayara-maria-da-silva', name: 'Nayara Maria Da Silva', avec_pro_id: '944918', role: 'other', active: true },
  { id: 'pro-brasil-nayara-poveda-xavier', name: 'Nayara Poveda Xavier', avec_pro_id: '936477', role: 'other', active: true },
  { id: 'pro-brasil-nicolas-yan-martins-da-silveira', name: 'Nicolas Yan Martins Da Silveira', avec_pro_id: '1113753', role: 'hairstylist', active: true },
  { id: 'pro-brasil-nicolle-de-oliveira-alves', name: 'Nicolle De Oliveira Alves', avec_pro_id: '748084', role: 'other', active: true },
  { id: 'pro-brasil-nicoly-de-melo-lima', name: 'Nicoly De Melo Lima', avec_pro_id: '1043442', role: 'other', active: true },
  { id: 'pro-brasil-noelia-ribeiro-dos-santos', name: 'Noelia Ribeiro Dos Santos', avec_pro_id: '590946', role: 'other', active: true },
  { id: 'pro-brasil-nubia-michelle-lira-da-silva', name: 'Nubia Michelle Lira Da Silva', avec_pro_id: '640921', role: 'other', active: true },
  { id: 'pro-brasil-pablo-malafaia-caetano', name: 'Pablo Malafaia Caetano', avec_pro_id: '919063', role: 'hairstylist', active: true },
  { id: 'pro-brasil-paloma-cavalcanti', name: 'Paloma Cavalcanti', avec_pro_id: '1076289', role: 'other', active: true },
  { id: 'pro-brasil-patricia-andrea-da-silva-joasen', name: 'Patricia Andrea Da Silva Joasen', avec_pro_id: '740749', role: 'other', active: true },
  { id: 'pro-brasil-patricia-barbosa-paixao-lopes', name: 'Patricia Barbosa Paixao Lopes', avec_pro_id: '564770', role: 'other', active: true },
  { id: 'pro-brasil-patricia-mara-nossig-de-carvalho', name: 'Patricia Mara Nossig De Carvalho', avec_pro_id: '983719', role: 'hairstylist', active: true },
  { id: 'pro-brasil-patricia-saraiva-savie', name: 'Patricia Saraiva (savie)', avec_pro_id: '995022', role: 'other', active: true },
  { id: 'pro-brasil-patrick-leal-de-jesus', name: 'Patrick Leal De Jesus', avec_pro_id: '1113800', role: 'other', active: true },
  { id: 'pro-brasil-paulo-roberto-ribeiro-domingues', name: 'Paulo Roberto Ribeiro Domingues', avec_pro_id: '1117747', role: 'other', active: true },
  { id: 'pro-brasil-pedro-diello', name: 'Pedro Diello', avec_pro_id: '564750', role: 'hairstylist', active: true },
  { id: 'pro-brasil-pedro-henrique-sousa-cardi', name: 'Pedro Henrique Sousa Cardi', avec_pro_id: '704436', role: 'other', active: true },
  { id: 'pro-brasil-pedro-oliveira-silva', name: 'Pedro Oliveira Silva', avec_pro_id: '992682', role: 'other', active: true },
  { id: 'pro-brasil-pedro-ricardo-galdi', name: 'Pedro Ricardo Galdi', avec_pro_id: '1076840', role: 'hairstylist', active: true },
  { id: 'pro-brasil-pierre-tawan-alves-franca', name: 'Pierre Tawan Alves Franca', avec_pro_id: '1055640', role: 'makeup', active: true },
  { id: 'pro-brasil-rafaella-edwiges-bernardo-nunes', name: 'Rafaella Edwiges Bernardo Nunes', avec_pro_id: '853817', role: 'makeup', active: true },
  { id: 'pro-brasil-raquel-azevedo-nina', name: 'Raquel Azevedo Nina', avec_pro_id: '861377', role: 'other', active: true },
  { id: 'pro-brasil-rayana-santiago-campos', name: 'Rayana Santiago Campos', avec_pro_id: '581991', role: 'other', active: true },
  { id: 'pro-brasil-rayssa-ferreira-da-costa', name: 'Rayssa  Ferreira Da Costa', avec_pro_id: '638701', role: 'other', active: true },
  { id: 'pro-brasil-rebecca-marques-cavalcante', name: 'Rebecca Marques Cavalcante', avec_pro_id: '1081763', role: 'other', active: true },
  { id: 'pro-brasil-renan-dos-santos-funchal-silva', name: 'Renan Dos Santos Funchal Silva', avec_pro_id: '1049212', role: 'hairstylist', active: true },
  { id: 'pro-brasil-renan-equipe-dh', name: 'Renan Equipe Dh', avec_pro_id: '1112713', role: 'other', active: true },
  { id: 'pro-brasil-ricardo-silva-santos', name: 'Ricardo Silva Santos', avec_pro_id: '1090358', role: 'other', active: true },
  { id: 'pro-brasil-rivania-e-victoria-rassan-joias', name: 'Rivania E Victoria Rassan (joias)', avec_pro_id: '995049', role: 'other', active: true },
  { id: 'pro-brasil-roberval-de-s-monteiro-servicos-cabeleireiros', name: 'Roberval De S. Monteiro Serviços Cabeleireiros', avec_pro_id: '879744', role: 'hairstylist', active: true },
  { id: 'pro-brasil-rodolfo-scarpelin-da-silva', name: 'Rodolfo Scarpelin Da Silva', avec_pro_id: '1011134', role: 'other', active: true },
  { id: 'pro-brasil-rodrigo-apolinario-pires-saraiva', name: 'Rodrigo Apolinario Pires Saraiva', avec_pro_id: '1011501', role: 'hairstylist', active: true },
  { id: 'pro-brasil-rodrigo-ezequiel-dos-santos', name: 'Rodrigo Ezequiel Dos Santos', avec_pro_id: '1045456', role: 'other', active: true },
  { id: 'pro-brasil-romeu-felipe', name: 'Romeu Felipe', avec_pro_id: '127335', role: 'hairstylist', active: true },
  { id: 'pro-brasil-rute-b-beltrao-martins', name: 'Rute B Beltrao Martins', avec_pro_id: '1061780', role: 'other', active: true },
  { id: 'pro-brasil-ruth-do-nascimento-abade', name: 'Ruth Do Nascimento Abade', avec_pro_id: '649500', role: 'other', active: true },
  { id: 'pro-brasil-ryan-pablo-da-silva-pereira', name: 'Ryan Pablo Da Silva Pereira', avec_pro_id: '991074', role: 'other', active: true },
  { id: 'pro-brasil-sabrina-ferreira-jordao', name: 'Sabrina Ferreira Jordao', avec_pro_id: '911293', role: 'other', active: true },
  { id: 'pro-brasil-sabrina-praxedes-marketing', name: 'Sabrina Praxedes (marketing)', avec_pro_id: '1011424', role: 'other', active: true },
  { id: 'pro-brasil-sandra-novaes-nascimento-dos-santos', name: 'Sandra Novaes Nascimento Dos Santos', avec_pro_id: '899638', role: 'other', active: true },
  { id: 'pro-brasil-secretaria-lu-amaro', name: 'Secretaria Lu Amaro', avec_pro_id: '716986', role: 'other', active: true },
  { id: 'pro-brasil-secretaria-marina-mattar', name: 'Secretaria Marina Mattar', avec_pro_id: '725768', role: 'other', active: true },
  { id: 'pro-brasil-secretaria-marina-mattar-1', name: 'Secretaria Marina Mattar 1', avec_pro_id: '728219', role: 'other', active: true },
  { id: 'pro-brasil-selma-guerra', name: 'Selma Guerra', avec_pro_id: '1117314', role: 'other', active: true },
  { id: 'pro-brasil-sidney-mauro-silva-canoto-da-cruz', name: 'Sidney Mauro Silva Canoto Da Cruz', avec_pro_id: '1035429', role: 'other', active: true },
  { id: 'pro-brasil-solange-franca-da-silva', name: 'Solange Franca Da Silva', avec_pro_id: '905485', role: 'other', active: true },
  { id: 'pro-brasil-solange-soares-de-souza', name: 'Solange Soares De Souza', avec_pro_id: '1113723', role: 'other', active: true },
  { id: 'pro-brasil-sonia-teixeira-chaves', name: 'Sonia Teixeira Chaves', avec_pro_id: '564754', role: 'other', active: true },
  { id: 'pro-brasil-taise-silva-leite', name: 'Taise Silva Leite', avec_pro_id: '946563', role: 'other', active: true },
  { id: 'pro-brasil-talita-a', name: 'Talita A.', avec_pro_id: '564756', role: 'hairstylist', active: true },
  { id: 'pro-brasil-talita-barros-valim-de-castro', name: 'Talita Barros Valim De Castro', avec_pro_id: '948087', role: 'makeup', active: true },
  { id: 'pro-brasil-talita-equipe-dh', name: 'Talita Equipe Dh', avec_pro_id: '1113310', role: 'other', active: true },
  { id: 'pro-brasil-tassiana-campelo-equipe-dh', name: 'Tassiana Campelo Equipe Dh', avec_pro_id: '1112711', role: 'other', active: true },
  { id: 'pro-brasil-tatiane-monteiro-silva', name: 'Tatiane Monteiro Silva', avec_pro_id: '1116854', role: 'other', active: true },
  { id: 'pro-brasil-tatiane-rodrigues-gomes-barroso', name: 'Tatiane Rodrigues Gomes Barroso', avec_pro_id: '1112430', role: 'other', active: true },
  { id: 'pro-brasil-terminal-salao', name: 'Terminal Salao', avec_pro_id: '564382', role: 'other', active: true },
  { id: 'pro-brasil-thais-da-silva-soares-gois', name: 'Thais Da Silva Soares Gois', avec_pro_id: '1061757', role: 'other', active: true },
  { id: 'pro-brasil-thais-harumi-honda', name: 'Thais Harumi Honda', avec_pro_id: '564758', role: 'hairstylist', active: true },
  { id: 'pro-brasil-thalita-gabrielle-balber-ribeiro', name: 'Thalita Gabrielle Balber Ribeiro', avec_pro_id: '933173', role: 'other', active: true },
  { id: 'pro-brasil-thayna-silva-dos-santos', name: 'Thayna Silva Dos Santos', avec_pro_id: '1104885', role: 'other', active: true },
  { id: 'pro-brasil-thiago-silva-de-jesus', name: 'Thiago Silva De Jesus', avec_pro_id: '992593', role: 'other', active: true },
  { id: 'pro-brasil-thiago-veloso', name: 'Thiago Veloso', avec_pro_id: '941717', role: 'other', active: true },
  { id: 'pro-brasil-thuane-barros-do-val', name: 'Thuane Barros Do Val', avec_pro_id: '632688', role: 'other', active: true },
  { id: 'pro-brasil-tiago-goncalves-menezes', name: 'Tiago Goncalves Menezes', avec_pro_id: '990020', role: 'other', active: true },
  { id: 'pro-brasil-ulisses-silva-junior', name: 'Ulisses Silva Junior', avec_pro_id: '564677', role: 'hairstylist', active: true },
  { id: 'pro-brasil-valeria-cardoso-de-oliveira', name: 'Valeria Cardoso De Oliveira', avec_pro_id: '889898', role: 'other', active: true },
  { id: 'pro-brasil-valeria-souza-bpo', name: 'Valeria Souza Bpo', avec_pro_id: '888209', role: 'other', active: true },
  { id: 'pro-brasil-vanessa-custodio-bronze', name: 'Vanessa Custodio (bronze)', avec_pro_id: '995046', role: 'other', active: true },
  { id: 'pro-brasil-victor-chaves-santos', name: 'Victor Chaves Santos', avec_pro_id: '1104283', role: 'other', active: true },
  { id: 'pro-brasil-victoria-rassan-joias', name: 'Victoria Rassan (joias)', avec_pro_id: '995048', role: 'other', active: true },
  { id: 'pro-brasil-vinicius-morais', name: 'Vinicius Morais', avec_pro_id: '870333', role: 'other', active: true },
  { id: 'pro-brasil-vitalino-pereira-campos', name: 'Vitalino Pereira Campos', avec_pro_id: '564681', role: 'hairstylist', active: true },
  { id: 'pro-brasil-vitor-moreira-de-alvarenga-morais', name: 'Vitor Moreira De Alvarenga Morais', avec_pro_id: '830330', role: 'hairstylist', active: true },
  { id: 'pro-brasil-vitor-rodrigo-ferreira-mattos', name: 'Vitor Rodrigo Ferreira Mattos', avec_pro_id: '1114816', role: 'other', active: true },
  { id: 'pro-brasil-vitoria-de-souza-viana-nogueira', name: 'Vitoria De Souza Viana Nogueira', avec_pro_id: '860198', role: 'other', active: true },
  { id: 'pro-brasil-vladimir-aparecido-de-jesus', name: 'Vladimir Aparecido De Jesus', avec_pro_id: '1116053', role: 'other', active: true },
  { id: 'pro-brasil-waleska-lima-equipe-dh', name: 'Waleska Lima Equipe Dh', avec_pro_id: '1112715', role: 'other', active: true },
  { id: 'pro-brasil-walter-junior', name: 'Walter Junior', avec_pro_id: '1110996', role: 'other', active: true },
  { id: 'pro-brasil-walter-martinho-leal-filho-cabeleireiro', name: 'Walter Martinho Leal Filho Cabeleireiro', avec_pro_id: '603096', role: 'hairstylist', active: true },
  { id: 'pro-brasil-wanderley-delcidio-da-silva', name: 'Wanderley Delcidio Da Silva', avec_pro_id: '564675', role: 'hairstylist', active: true },
  { id: 'pro-brasil-warley-alberto-soares', name: 'Warley Alberto Soares', avec_pro_id: '1005358', role: 'other', active: true },
  { id: 'pro-brasil-weliton-vicente-de-lima', name: 'Weliton Vicente De Lima', avec_pro_id: '1117748', role: 'other', active: true },
  { id: 'pro-brasil-willian-da-silva-leal', name: 'Willian Da Silva Leal', avec_pro_id: '947101', role: 'other', active: true },
  { id: 'pro-brasil-willyan-thiago-franco-sass', name: 'Willyan Thiago Franco Sass', avec_pro_id: '896407', role: 'other', active: true },
  { id: 'pro-brasil-yasmin-borsani-abdouni', name: 'Yasmin Borsani Abdouni', avec_pro_id: '1026554', role: 'other', active: true },
]
