import type { DirectorProfessional } from './types'

/** Roster ATIVO gerado do AvecLake (salao_id=99801). */
export const IGUATEMI_DIRECTOR_PROFESSIONALS: DirectorProfessional[] = [
  { id: 'pro-iguatemi-andressa-erica-batista-de-oliveira', name: 'Andressa Erica Batista De Oliveira', avec_pro_id: '918240', role: 'other', active: true },
  { id: 'pro-iguatemi-augusto-alan-avec', name: 'Augusto Alan ( Avec)', avec_pro_id: '917292', role: 'other', active: true },
  { id: 'pro-iguatemi-beto-fortes', name: 'Beto Fortes', avec_pro_id: '1061660', role: 'hairstylist', active: true },
  { id: 'pro-iguatemi-daniel-viana-martins', name: 'Daniel Viana Martins', avec_pro_id: '913274', role: 'hairstylist', active: true },
  { id: 'pro-iguatemi-ewerton-emanuel-costa-scremim', name: 'Ewerton Emanuel Costa Scremim', avec_pro_id: '1104465', role: 'other', active: true },
  { id: 'pro-iguatemi-gabriela-da-silva-santos', name: 'Gabriela Da Silva  Santos', avec_pro_id: '913229', role: 'other', active: true },
  { id: 'pro-iguatemi-abigail-erculano-da-silva', name: 'Abigail  Erculano  Da Silva', avec_pro_id: '1020759', role: 'other', active: true },
  { id: 'pro-iguatemi-alan-fernando-de-albuquerque', name: 'Alan Fernando De Albuquerque', avec_pro_id: '1050084', role: 'hairstylist', active: true },
  { id: 'pro-iguatemi-alessandra-cristina-fernandes-aguiar', name: 'Alessandra Cristina Fernandes Aguiar', avec_pro_id: '913047', role: 'hairstylist', active: true },
  { id: 'pro-iguatemi-almoxarifado-iguatemi', name: 'Almoxarifado Iguatemi', avec_pro_id: '1004173', role: 'other', active: true },
  { id: 'pro-iguatemi-amanda-carolina-de-souza-marketing', name: 'Amanda Carolina De Souza (marketing)', avec_pro_id: '983153', role: 'other', active: true },
  { id: 'pro-iguatemi-amanda-dos-santos-araujo', name: 'Amanda Dos Santos Araujo', avec_pro_id: '1005515', role: 'other', active: true },
  { id: 'pro-iguatemi-amanda-karine-costa-de-sousa', name: 'Amanda Karine Costa De Sousa', avec_pro_id: '918534', role: 'hairstylist', active: true },
  { id: 'pro-iguatemi-amauri-baptista-bezerra', name: 'Amauri Baptista Bezerra', avec_pro_id: '913253', role: 'hairstylist', active: true },
  { id: 'pro-iguatemi-ana-cristina-matsumoto', name: 'Ana Cristina Matsumoto', avec_pro_id: '918749', role: 'hairstylist', active: true },
  { id: 'pro-iguatemi-ananda-pinheiro-ferraz', name: 'Ananda Pinheiro Ferraz', avec_pro_id: '1118931', role: 'other', active: true },
  { id: 'pro-iguatemi-anderson-augusto', name: 'Anderson Augusto', avec_pro_id: '918694', role: 'makeup', active: true },
  { id: 'pro-iguatemi-andre-brito', name: 'André Brito', avec_pro_id: '918901', role: 'other', active: true },
  { id: 'pro-iguatemi-andre-luiz-martins-de-paula', name: 'André Luiz Martins De Paula', avec_pro_id: '918631', role: 'other', active: true },
  { id: 'pro-iguatemi-angela-cristina-barbosa', name: 'Angela Cristina Barbosa', avec_pro_id: '1074750', role: 'other', active: true },
  { id: 'pro-iguatemi-ariane-cristina-dos-santos', name: 'Ariane Cristina  Dos Santos', avec_pro_id: '913284', role: 'other', active: true },
  { id: 'pro-iguatemi-auricaliane-dantas-da-silva', name: 'Auricaliane Dantas Da Silva', avec_pro_id: '965672', role: 'other', active: true },
  { id: 'pro-iguatemi-barbara-duarte-sousa-silva', name: 'Barbara Duarte Sousa Silva', avec_pro_id: '986861', role: 'other', active: true },
  { id: 'pro-iguatemi-brida-souza-pontes', name: 'Brida Souza Pontes', avec_pro_id: '1115833', role: 'other', active: true },
  { id: 'pro-iguatemi-bruna-gomes-irineu', name: 'Bruna Gomes Irineu', avec_pro_id: '1061777', role: 'other', active: true },
  { id: 'pro-iguatemi-brunna-fabricio-da-silva', name: 'Brunna Fabricio Da Silva', avec_pro_id: '912971', role: 'hairstylist', active: true },
  { id: 'pro-iguatemi-caio-de-lima-carvalho', name: 'Caio  De Lima Carvalho', avec_pro_id: '913286', role: 'other', active: true },
  { id: 'pro-iguatemi-camila-novais-santos', name: 'Camila Novais  Santos', avec_pro_id: '918437', role: 'other', active: true },
  { id: 'pro-iguatemi-camila-ornelas-santos', name: 'Camila Ornelas Santos', avec_pro_id: '912981', role: 'hairstylist', active: true },
  { id: 'pro-iguatemi-camila-sartorato-burgarelli', name: 'Camila Sartorato Burgarelli', avec_pro_id: '912982', role: 'hairstylist', active: true },
  { id: 'pro-iguatemi-carina-fernanda-de-freitas-ferreira', name: 'Carina Fernanda De Freitas Ferreira', avec_pro_id: '935421', role: 'hairstylist', active: true },
  { id: 'pro-iguatemi-carlos-vinicius-borges', name: 'Carlos Vinicius Borges', avec_pro_id: '913289', role: 'other', active: true },
  { id: 'pro-iguatemi-caroline-vieira-lopes', name: 'Caroline Vieira Lopes', avec_pro_id: '1094312', role: 'other', active: true },
  { id: 'pro-iguatemi-celia-de-castro-meneses', name: 'Celia De Castro Meneses', avec_pro_id: '913248', role: 'makeup', active: true },
  { id: 'pro-iguatemi-charles-averlan-ferreira-do-nascimento', name: 'Charles Averlan Ferreira Do Nascimento', avec_pro_id: '1114573', role: 'other', active: true },
  { id: 'pro-iguatemi-charles-veiyga-consultoria-e-treinamento-de-moda-e-beleza', name: 'Charles Veiyga Consultoria E Treinamento De Moda E Beleza', avec_pro_id: '935810', role: 'hairstylist', active: true },
  { id: 'pro-iguatemi-chefe-lucas-jonathan', name: 'Chefe Lucas Jonathan', avec_pro_id: '1112802', role: 'other', active: true },
  { id: 'pro-iguatemi-cintia-da-silva-santos', name: 'Cintia Da Silva  Santos', avec_pro_id: '918449', role: 'other', active: true },
  { id: 'pro-iguatemi-claudiana-bezerra-da-silva', name: 'Claudiana Bezerra Da Silva', avec_pro_id: '913235', role: 'hairstylist', active: true },
  { id: 'pro-iguatemi-clayton-mozar-alves-de-oliveira', name: 'Clayton Mozar Alves De Oliveira', avec_pro_id: '1013042', role: 'hairstylist', active: true },
  { id: 'pro-iguatemi-contabil', name: 'Contabil', avec_pro_id: '913070', role: 'other', active: true },
  { id: 'pro-iguatemi-dailza-magalhaes-dos-santos', name: 'Dailza Magalhaes Dos Santos', avec_pro_id: '1090654', role: 'other', active: true },
  { id: 'pro-iguatemi-daniel-chabaribery', name: 'Daniel Chabaribery', avec_pro_id: '1024847', role: 'hairstylist', active: true },
  { id: 'pro-iguatemi-daniel-da-silva-santos', name: 'Daniel Da Silva Santos', avec_pro_id: '1115039', role: 'other', active: true },
  { id: 'pro-iguatemi-daniel-souza-da-silva', name: 'Daniel Souza Da Silva', avec_pro_id: '1032041', role: 'other', active: true },
  { id: 'pro-iguatemi-daniela-machado-rocha', name: 'Daniela Machado Rocha', avec_pro_id: '913234', role: 'hairstylist', active: true },
  { id: 'pro-iguatemi-david-barbosa-da-silva', name: 'David Barbosa Da Silva', avec_pro_id: '913265', role: 'other', active: true },
  { id: 'pro-iguatemi-deise-de-araujo-reis', name: 'Deise De Araujo Reis', avec_pro_id: '954204', role: 'other', active: true },
  { id: 'pro-iguatemi-deise-de-assis-santana', name: 'Deise De Assis Santana', avec_pro_id: '918237', role: 'other', active: true },
  { id: 'pro-iguatemi-dhandara-vieira-gomes', name: 'Dhandara Vieira Gomes', avec_pro_id: '918242', role: 'other', active: true },
  { id: 'pro-iguatemi-diana-dos-anjos-santos', name: 'Diana Dos Anjos Santos', avec_pro_id: '918646', role: 'other', active: true },
  { id: 'pro-iguatemi-diana-dos-santos-cavalcanti-beleza-das-maos', name: 'Diana Dos Santos Cavalcanti Beleza Das Mãos', avec_pro_id: '913238', role: 'other', active: true },
  { id: 'pro-iguatemi-diego-rodrigues-de-morais', name: 'Diego Rodrigues De Morais', avec_pro_id: '1102021', role: 'other', active: true },
  { id: 'pro-iguatemi-douglas-eduardo-rossi', name: 'Douglas Eduardo Rossi', avec_pro_id: '1033882', role: 'hairstylist', active: true },
  { id: 'pro-iguatemi-edgar-gomes-dos-santos', name: 'Edgar Gomes Dos Santos', avec_pro_id: '1102048', role: 'other', active: true },
  { id: 'pro-iguatemi-edijane-maria-de-macedo', name: 'Edijane Maria De Macedo', avec_pro_id: '913270', role: 'other', active: true },
  { id: 'pro-iguatemi-ednilson-pantoja-filho', name: 'Ednilson Pantoja Filho', avec_pro_id: '960119', role: 'other', active: true },
  { id: 'pro-iguatemi-eduardo-costa-vale', name: 'Eduardo Costa Vale', avec_pro_id: '1117725', role: 'other', active: true },
  { id: 'pro-iguatemi-elaine-de-oliveira', name: 'Elaine De Oliveira', avec_pro_id: '1101205', role: 'other', active: true },
  { id: 'pro-iguatemi-elaine-fernandes-pires', name: 'Elaine Fernandes Pires', avec_pro_id: '1102051', role: 'other', active: true },
  { id: 'pro-iguatemi-elaine-moraes', name: 'Elaine Moraes', avec_pro_id: '900878', role: 'other', active: true },
  { id: 'pro-iguatemi-elisangela-menezes-dos-santos', name: 'Elisangela Menezes Dos Santos', avec_pro_id: '1052168', role: 'other', active: true },
  { id: 'pro-iguatemi-eliseu-vicente-da-conceicao', name: 'Eliseu Vicente Da Conceicao', avec_pro_id: '965675', role: 'other', active: true },
  { id: 'pro-iguatemi-elivaine-de-lourdes-sousa', name: 'Elivaine De Lourdes Sousa', avec_pro_id: '1105958', role: 'other', active: true },
  { id: 'pro-iguatemi-elvis-santos', name: 'Elvis Santos', avec_pro_id: '920196', role: 'other', active: true },
  { id: 'pro-iguatemi-emanuel-antonio-modena', name: 'Emanuel Antonio Modena', avec_pro_id: '912987', role: 'hairstylist', active: true },
  { id: 'pro-iguatemi-emanuela-campos-de-moura', name: 'Emanuela Campos De Moura', avec_pro_id: '918692', role: 'hairstylist', active: true },
  { id: 'pro-iguatemi-ers-contabilidade', name: 'Ers Contabilidade', avec_pro_id: '1114290', role: 'other', active: true },
  { id: 'pro-iguatemi-evandro-carlos-pires', name: 'Evandro Carlos Pires', avec_pro_id: '1083884', role: 'other', active: true },
  { id: 'pro-iguatemi-f-roberval-de-s-monteiro-servicos-cabeleireiros', name: 'F. Roberval De S. Monteiro Serviços Cabeleireiros', avec_pro_id: '913272', role: 'hairstylist', active: true },
  { id: 'pro-iguatemi-fabiane-rezende-simoes', name: 'Fabiane Rezende Simões', avec_pro_id: '1050736', role: 'other', active: true },
  { id: 'pro-iguatemi-felipe-gabriel-ferreira-lima-manutencao', name: 'Felipe Gabriel Ferreira Lima (manutenção)', avec_pro_id: '1003913', role: 'other', active: true },
  { id: 'pro-iguatemi-fernanda-de-lima-pereira', name: 'Fernanda De Lima Pereira', avec_pro_id: '1065527', role: 'other', active: true },
  { id: 'pro-iguatemi-fernanda-dos-santos-cerqueira', name: 'Fernanda Dos Santos Cerqueira', avec_pro_id: '918234', role: 'other', active: true },
  { id: 'pro-iguatemi-fernanda-magalhaes-araujo', name: 'Fernanda Magalhães Araujo', avec_pro_id: '1101125', role: 'other', active: true },
  { id: 'pro-iguatemi-fernanda-patricia-cezar-de-andrade', name: 'Fernanda Patricia Cezar De Andrade', avec_pro_id: '950117', role: 'other', active: true },
  { id: 'pro-iguatemi-financeiro-anderson-fonseca-de-oliveira', name: 'Financeiro - Anderson Fonseca De Oliveira', avec_pro_id: '950088', role: 'other', active: true },
  { id: 'pro-iguatemi-financeiro-karina-marques', name: 'Financeiro - Karina Marques', avec_pro_id: '913201', role: 'other', active: true },
  { id: 'pro-iguatemi-francileide-melo-dos-santos', name: 'Francileide Melo Dos Santos', avec_pro_id: '1117414', role: 'other', active: true },
  { id: 'pro-iguatemi-francisca-meireles-do-nascimento', name: 'Francisca Meireles Do Nascimento', avec_pro_id: '913257', role: 'other', active: true },
  { id: 'pro-iguatemi-francyele-de-souza-oliveira-santos', name: 'Francyele De Souza Oliveira Santos', avec_pro_id: '1048996', role: 'other', active: true },
  { id: 'pro-iguatemi-gabriel-john-dos-santos', name: 'Gabriel John Dos Santos', avec_pro_id: '912993', role: 'hairstylist', active: true },
  { id: 'pro-iguatemi-gabriel-muniz-kopezynski', name: 'Gabriel Muniz Kopezynski', avec_pro_id: '1102046', role: 'other', active: true },
  { id: 'pro-iguatemi-gabriela-martins-da-silva', name: 'Gabriela Martins Da Silva', avec_pro_id: '925666', role: 'other', active: true },
  { id: 'pro-iguatemi-geisa-barbosa-dos-santos', name: 'Geisa Barbosa Dos Santos', avec_pro_id: '918434', role: 'other', active: true },
  { id: 'pro-iguatemi-george-henrique-da-silva', name: 'George Henrique Da Silva', avec_pro_id: '918576', role: 'hairstylist', active: true },
  { id: 'pro-iguatemi-gildenice-teixeira-de-medeiros', name: 'Gildenice Teixeira De Medeiros', avec_pro_id: '913256', role: 'hairstylist', active: true },
  { id: 'pro-iguatemi-giovani-miranda-garcia', name: 'Giovani Miranda Garcia', avec_pro_id: '912995', role: 'hairstylist', active: true },
  { id: 'pro-iguatemi-giovanna-silva-oliveira', name: 'Giovanna Silva Oliveira', avec_pro_id: '1102324', role: 'other', active: true },
  { id: 'pro-iguatemi-gisele-greyce-lima-faglioni', name: 'Gisele Greyce Lima Faglioni', avec_pro_id: '913211', role: 'makeup', active: true },
  { id: 'pro-iguatemi-gislaine-pedrosa-rodrigues', name: 'Gislaine Pedrosa Rodrigues', avec_pro_id: '1093915', role: 'other', active: true },
  { id: 'pro-iguatemi-graciele-da-silva-santos', name: 'Graciele Da Silva Santos', avec_pro_id: '912996', role: 'other', active: true },
  { id: 'pro-iguatemi-guilherme-machado-souza', name: 'Guilherme Machado Souza', avec_pro_id: '912997', role: 'hairstylist', active: true },
  { id: 'pro-iguatemi-gustavo-fontes-de-oliveira', name: 'Gustavo Fontes De Oliveira', avec_pro_id: '913277', role: 'hairstylist', active: true },
  { id: 'pro-iguatemi-higor-vinicius-pinto-silva', name: 'Higor Vinicius Pinto Silva', avec_pro_id: '1052606', role: 'other', active: true },
  { id: 'pro-iguatemi-ingrid-silva-barreto', name: 'Ingrid Silva Barreto', avec_pro_id: '913275', role: 'other', active: true },
  { id: 'pro-iguatemi-isabella-acioli-nato-da-silva', name: 'Isabella Acioli Nato Da Silva', avec_pro_id: '918177', role: 'other', active: true },
  { id: 'pro-iguatemi-isabella-de-paula-santos', name: 'Isabella De Paula Santos', avec_pro_id: '1037073', role: 'other', active: true },
  { id: 'pro-iguatemi-isabelly-sousa-da-silva', name: 'Isabelly Sousa Da Silva', avec_pro_id: '1106023', role: 'other', active: true },
  { id: 'pro-iguatemi-izabela-de-sousa-gomes', name: 'Izabela De Sousa Gomes', avec_pro_id: '1117729', role: 'other', active: true },
  { id: 'pro-iguatemi-jacinta-maciel-da-silva', name: 'Jacinta Maciel Da Silva', avec_pro_id: '962436', role: 'other', active: true },
  { id: 'pro-iguatemi-janaina-cristina-alves-da-silva', name: 'Janaina Cristina Alves Da Silva', avec_pro_id: '912998', role: 'other', active: true },
  { id: 'pro-iguatemi-janaina-santana-perreira', name: 'Janaina Santana Perreira', avec_pro_id: '1059623', role: 'hairstylist', active: true },
  { id: 'pro-iguatemi-janali-do-nascimento-cruz', name: 'Janali Do Nascimento Cruz', avec_pro_id: '913239', role: 'other', active: true },
  { id: 'pro-iguatemi-jaqueline-fernandes-de-melo', name: 'Jaqueline Fernandes De Melo', avec_pro_id: '918174', role: 'other', active: true },
  { id: 'pro-iguatemi-jaqueline-ribeiro-dos-santos', name: 'Jaqueline Ribeiro Dos Santos', avec_pro_id: '1050097', role: 'other', active: true },
  { id: 'pro-iguatemi-jayne-fernandes-de-melo', name: 'Jayne Fernandes De Melo', avec_pro_id: '926986', role: 'other', active: true },
  { id: 'pro-iguatemi-jefferson-policarpo-dos-santos', name: 'Jefferson Policarpo Dos Santos', avec_pro_id: '913293', role: 'other', active: true },
  { id: 'pro-iguatemi-jefferson-scaraficci-goiabeira', name: 'Jefferson Scaraficci Goiabeira', avec_pro_id: '1016884', role: 'other', active: true },
  { id: 'pro-iguatemi-jessica-caroline-alves-machado', name: 'Jessica Caroline Alves Machado', avec_pro_id: '1100887', role: 'other', active: true },
  { id: 'pro-iguatemi-jessica-layne-diniz-vilela', name: 'Jessica Layne Diniz Vilela', avec_pro_id: '1082525', role: 'other', active: true },
  { id: 'pro-iguatemi-jessica-silva-freitas', name: 'Jessica Silva Freitas', avec_pro_id: '918444', role: 'other', active: true },
  { id: 'pro-iguatemi-jislayne-rodrigues-de-arruda', name: 'Jislayne Rodrigues De Arruda', avec_pro_id: '1100825', role: 'other', active: true },
  { id: 'pro-iguatemi-joanides-mendes-pontes-junior', name: 'Joanides Mendes Pontes Junior', avec_pro_id: '995408', role: 'hairstylist', active: true },
  { id: 'pro-iguatemi-johnatan-de-souza-santana', name: 'Johnatan De Souza Santana', avec_pro_id: '965673', role: 'other', active: true },
  { id: 'pro-iguatemi-jonathan-araujo-nunes', name: 'Jonathan Araujo Nunes', avec_pro_id: '1070239', role: 'hairstylist', active: true },
  { id: 'pro-iguatemi-jonathan-dias-dos-santos', name: 'Jonathan Dias Dos Santos', avec_pro_id: '1005806', role: 'other', active: true },
  { id: 'pro-iguatemi-jonathan-lucas-santos-nunes', name: 'Jonathan Lucas Santos Nunes', avec_pro_id: '1057265', role: 'other', active: true },
  { id: 'pro-iguatemi-joseilma-correia-de-barros-de-oliveira', name: 'Joseilma Correia De Barros De Oliveira', avec_pro_id: '918700', role: 'other', active: true },
  { id: 'pro-iguatemi-josineire-alice-ferreira', name: 'Josineire Alice Ferreira', avec_pro_id: '1102022', role: 'other', active: true },
  { id: 'pro-iguatemi-jose-antonio-dias-de-carvalho', name: 'José Antonio Dias De Carvalho', avec_pro_id: '913003', role: 'other', active: true },
  { id: 'pro-iguatemi-jose-lumbo-cotingo', name: 'José Lumbo Cotingo', avec_pro_id: '920510', role: 'other', active: true },
  { id: 'pro-iguatemi-joyce-alves', name: 'Joyce Alves', avec_pro_id: '920146', role: 'other', active: true },
  { id: 'pro-iguatemi-joao-carlos-da-silva-lima', name: 'João Carlos Da Silva Lima', avec_pro_id: '1068575', role: 'other', active: true },
  { id: 'pro-iguatemi-joao-felipe-candido-da-silva-marketing', name: 'João Felipe Cândido Da Silva (marketing)', avec_pro_id: '1016755', role: 'other', active: true },
  { id: 'pro-iguatemi-joao-vitor-bispo-dos-santos', name: 'João Vitor Bispo Dos Santos', avec_pro_id: '1027830', role: 'other', active: true },
  { id: 'pro-iguatemi-julia-alves-goncalves', name: 'Julia Alves Gonçalves', avec_pro_id: '1074671', role: 'other', active: true },
  { id: 'pro-iguatemi-juliane-vizoni', name: 'Juliane Vizoni', avec_pro_id: '995858', role: 'other', active: true },
  { id: 'pro-iguatemi-julio-cesar-alves-de-franca', name: 'Julio Cesar Alves De Franca', avec_pro_id: '973963', role: 'other', active: true },
  { id: 'pro-iguatemi-jussara-vitoria-santos-frade', name: 'Jussara Vitoria Santos Frade', avec_pro_id: '1121675', role: 'other', active: true },
  { id: 'pro-iguatemi-jussimara-santos-da-silva', name: 'Jussimara Santos Da Silva', avec_pro_id: '1102053', role: 'other', active: true },
  { id: 'pro-iguatemi-junior-santos', name: 'Júnior Santos', avec_pro_id: '948201', role: 'hairstylist', active: true },
  { id: 'pro-iguatemi-kamilla-fernandes-leite', name: 'Kamilla Fernandes Leite', avec_pro_id: '918929', role: 'hairstylist', active: true },
  { id: 'pro-iguatemi-laudenilva-dos-santos-silva', name: 'Laudenilva Dos Santos Silva', avec_pro_id: '1035043', role: 'hairstylist', active: true },
  { id: 'pro-iguatemi-leandro-santos-marques', name: 'Leandro Santos Marques', avec_pro_id: '913245', role: 'other', active: true },
  { id: 'pro-iguatemi-leda-maria-rocha-cavalcanti-silva', name: 'Leda Maria Rocha Cavalcanti Silva', avec_pro_id: '1051248', role: 'other', active: true },
  { id: 'pro-iguatemi-leiane-correia-leitao-avila', name: 'Leiane Correia Leitão Ávila', avec_pro_id: '913230', role: 'hairstylist', active: true },
  { id: 'pro-iguatemi-leiliane-luz-dos-santos', name: 'Leiliane Luz Dos Santos', avec_pro_id: '913241', role: 'other', active: true },
  { id: 'pro-iguatemi-leticia-custodio-pereira', name: 'Leticia Custodio Pereira', avec_pro_id: '918704', role: 'hairstylist', active: true },
  { id: 'pro-iguatemi-leticia-dantas-oliveira', name: 'Leticia Dantas Oliveira', avec_pro_id: '913049', role: 'other', active: true },
  { id: 'pro-iguatemi-leticia-firmino-da-silva', name: 'Leticia Firmino Da Silva', avec_pro_id: '1020346', role: 'other', active: true },
  { id: 'pro-iguatemi-liria-pereira-colman', name: 'Liria Pereira Colman', avec_pro_id: '913236', role: 'other', active: true },
  { id: 'pro-iguatemi-luan-aniello-franca-porreca-utiyama', name: 'Luan Aniello França Porreca Utiyama', avec_pro_id: '920509', role: 'other', active: true },
  { id: 'pro-iguatemi-luan-faustino-goncalves', name: 'Luan Faustino Gonçalves', avec_pro_id: '920195', role: 'other', active: true },
  { id: 'pro-iguatemi-luana-teixeira-jesus-dos-santos', name: 'Luana Teixeira Jesus Dos Santos', avec_pro_id: '992783', role: 'other', active: true },
  { id: 'pro-iguatemi-lucas-rodrigues-de-souza', name: 'Lucas Rodrigues De Souza', avec_pro_id: '912935', role: 'other', active: true },
  { id: 'pro-iguatemi-luis-gustavo-ribeiro-silvano', name: 'Luis Gustavo Ribeiro Silvano', avec_pro_id: '1003917', role: 'other', active: true },
  { id: 'pro-iguatemi-luziene-suely-mateus', name: 'Luziene Suely Mateus', avec_pro_id: '913278', role: 'other', active: true },
  { id: 'pro-iguatemi-marcela-de-araujo-guedes', name: 'Marcela De Araujo Guedes', avec_pro_id: '912957', role: 'hairstylist', active: true },
  { id: 'pro-iguatemi-marcelo-harpa', name: 'Marcelo Harpa', avec_pro_id: '913251', role: 'hairstylist', active: true },
  { id: 'pro-iguatemi-marco-aurelio-oliveira-carneiro', name: 'Marco Aurelio Oliveira Carneiro', avec_pro_id: '1115632', role: 'other', active: true },
  { id: 'pro-iguatemi-mari-eliz-de-oliveira-bueno', name: 'Mari Eliz De Oliveira Bueno', avec_pro_id: '1117408', role: 'other', active: true },
  { id: 'pro-iguatemi-maria-aparecida-rodrigues', name: 'Maria Aparecida Rodrigues', avec_pro_id: '913012', role: 'hairstylist', active: true },
  { id: 'pro-iguatemi-maria-auxiliadora-ribeiro-alves-alci', name: 'Maria Auxiliadora Ribeiro Alves Alci', avec_pro_id: '1010690', role: 'other', active: true },
  { id: 'pro-iguatemi-maria-das-dores-de-lima', name: 'Maria Das Dores De Lima', avec_pro_id: '1119543', role: 'other', active: true },
  { id: 'pro-iguatemi-maria-eduarda-cordeiro-gomes', name: 'Maria Eduarda Cordeiro Gomes', avec_pro_id: '1050417', role: 'other', active: true },
  { id: 'pro-iguatemi-maria-fernanda-da-conceicao', name: 'Maria Fernanda Da Conceição', avec_pro_id: '913128', role: 'other', active: true },
  { id: 'pro-iguatemi-maria-jilvania-pereira-de-santana', name: 'Maria Jilvania Pereira De Santana', avec_pro_id: '957427', role: 'other', active: true },
  { id: 'pro-iguatemi-maria-roseane-ferreira-duarte', name: 'Maria Roseane Ferreira Duarte', avec_pro_id: '913252', role: 'makeup', active: true },
  { id: 'pro-iguatemi-maria-valquiria-diogo', name: 'Maria Valquiria Diogo', avec_pro_id: '918173', role: 'other', active: true },
  { id: 'pro-iguatemi-mariane-carrenho', name: 'Mariane Carrenho', avec_pro_id: '931191', role: 'other', active: true },
  { id: 'pro-iguatemi-marilia-carneiro-de-brito', name: 'Marilia Carneiro De Brito', avec_pro_id: '913247', role: 'makeup', active: true },
  { id: 'pro-iguatemi-marina-alves-da-silva', name: 'Marina Alves Da Silva', avec_pro_id: '992159', role: 'other', active: true },
  { id: 'pro-iguatemi-marli-martins-de-oliveira', name: 'Marli Martins De Oliveira', avec_pro_id: '1047385', role: 'other', active: true },
  { id: 'pro-iguatemi-mateus-rodrigues-do-nascimento-da-silva', name: 'Mateus Rodrigues Do Nascimento Da Silva', avec_pro_id: '1102018', role: 'other', active: true },
  { id: 'pro-iguatemi-matheus-lemos-lessa', name: 'Matheus Lemos Lessa', avec_pro_id: '971903', role: 'other', active: true },
  { id: 'pro-iguatemi-mayara-muniz-pereira', name: 'Mayara Muniz Pereira', avec_pro_id: '1050088', role: 'other', active: true },
  { id: 'pro-iguatemi-maykon-luiz-dos-santos-cardozo', name: 'Maykon Luiz Dos Santos Cardozo', avec_pro_id: '913276', role: 'hairstylist', active: true },
  { id: 'pro-iguatemi-millena-costa-santos-da-cruz', name: 'Millena Costa Santos Da Cruz', avec_pro_id: '961567', role: 'other', active: true },
  { id: 'pro-iguatemi-milly-maia-bezerra', name: 'Milly Maia Bezerra', avec_pro_id: '966869', role: 'other', active: true },
  { id: 'pro-iguatemi-monique-lia-buna-castro-dos-santos', name: 'Monique Lia Buna Castro Dos Santos', avec_pro_id: '912952', role: 'hairstylist', active: true },
  { id: 'pro-iguatemi-narcelho-alves-santos', name: 'Narcelho Alves Santos', avec_pro_id: '918165', role: 'hairstylist', active: true },
  { id: 'pro-iguatemi-nicole-silva-podestar', name: 'Nicole Silva Podestar', avec_pro_id: '1039886', role: 'other', active: true },
  { id: 'pro-iguatemi-nicoly-de-melo-lima', name: 'Nicoly De Melo Lima', avec_pro_id: '1043444', role: 'other', active: true },
  { id: 'pro-iguatemi-orlando-lucas-rosa-alves-da-silva', name: 'Orlando Lucas Rosa Alves Da Silva', avec_pro_id: '959793', role: 'hairstylist', active: true },
  { id: 'pro-iguatemi-paloma-da-silva-cavalcanti', name: 'Paloma Da Silva Cavalcanti', avec_pro_id: '1073904', role: 'other', active: true },
  { id: 'pro-iguatemi-patricia-aguiar-pinto', name: 'Patricia Aguiar Pinto', avec_pro_id: '913271', role: 'other', active: true },
  { id: 'pro-iguatemi-paula-ana-domene', name: 'Paula Ana Domene', avec_pro_id: '1005404', role: 'other', active: true },
  { id: 'pro-iguatemi-pedro-e-f-diello', name: 'Pedro E F Diello', avec_pro_id: '961196', role: 'hairstylist', active: true },
  { id: 'pro-iguatemi-pedro-henrique-alencar-veloso', name: 'Pedro Henrique Alencar Veloso', avec_pro_id: '1114574', role: 'other', active: true },
  { id: 'pro-iguatemi-pedro-henrique-de-avila-sousa', name: 'Pedro Henrique De Avila Sousa', avec_pro_id: '1009364', role: 'other', active: true },
  { id: 'pro-iguatemi-pedro-henrique-oliveira-chagas', name: 'Pedro Henrique Oliveira Chagas', avec_pro_id: '920199', role: 'other', active: true },
  { id: 'pro-iguatemi-pedro-henrique-sousa-cardi', name: 'Pedro Henrique Sousa Cardi', avec_pro_id: '913120', role: 'other', active: true },
  { id: 'pro-iguatemi-pedro-victor-figueiredo-pinheiro', name: 'Pedro Victor Figueiredo Pinheiro', avec_pro_id: '951061', role: 'hairstylist', active: true },
  { id: 'pro-iguatemi-rafaela-sales-brito', name: 'Rafaela Sales Brito', avec_pro_id: '918439', role: 'other', active: true },
  { id: 'pro-iguatemi-rafaele-fonseca', name: 'Rafaele Fonseca', avec_pro_id: '913282', role: 'other', active: true },
  { id: 'pro-iguatemi-rafaella-edwiges-bernardo-nunes', name: 'Rafaella Edwiges Bernardo Nunes', avec_pro_id: '913255', role: 'makeup', active: true },
  { id: 'pro-iguatemi-ray-da-silva-sousa', name: 'Ray Da Silva Sousa', avec_pro_id: '1121310', role: 'other', active: true },
  { id: 'pro-iguatemi-rayane-de-jesus-souza', name: 'Rayane De Jesus Souza', avec_pro_id: '997626', role: 'other', active: true },
  { id: 'pro-iguatemi-rayane-ferreira-duarte', name: 'Rayane Ferreira Duarte', avec_pro_id: '918752', role: 'hairstylist', active: true },
  { id: 'pro-iguatemi-renan-da-silva-santos', name: 'Renan Da Silva Santos', avec_pro_id: '977002', role: 'other', active: true },
  { id: 'pro-iguatemi-ricardo-reinaldo-de-sousa', name: 'Ricardo Reinaldo De Sousa', avec_pro_id: '920197', role: 'other', active: true },
  { id: 'pro-iguatemi-ricardo-silva-santos', name: 'Ricardo Silva Santos', avec_pro_id: '1090868', role: 'other', active: true },
  { id: 'pro-iguatemi-roberto-aparecido-dos-santos', name: 'Roberto Aparecido Dos Santos', avec_pro_id: '948996', role: 'other', active: true },
  { id: 'pro-iguatemi-rodolfo-scarpelin-da-silva', name: 'Rodolfo Scarpelin Da Silva', avec_pro_id: '919228', role: 'other', active: true },
  { id: 'pro-iguatemi-rodrigo-ezequiel-dos-santos', name: 'Rodrigo Ezequiel Dos Santos', avec_pro_id: '1045464', role: 'other', active: true },
  { id: 'pro-iguatemi-rodrigo-goncalves-santiago-de-oliveira', name: 'Rodrigo Gonçalves Santiago De Oliveira', avec_pro_id: '1115652', role: 'other', active: true },
  { id: 'pro-iguatemi-romeu-felipe', name: 'Romeu Felipe', avec_pro_id: '912433', role: 'hairstylist', active: true },
  { id: 'pro-iguatemi-ronaldi-matos-de-ribeiro', name: 'Ronaldi Matos De Ribeiro', avec_pro_id: '1077013', role: 'other', active: true },
  { id: 'pro-iguatemi-ronekelly-farias-da-silva', name: 'Ronekelly Farias Da Silva', avec_pro_id: '912948', role: 'hairstylist', active: true },
  { id: 'pro-iguatemi-rosangela-aparecida-dos-santos', name: 'Rosangela Aparecida Dos Santos', avec_pro_id: '1104486', role: 'other', active: true },
  { id: 'pro-iguatemi-rute-b-beltrao-martins', name: 'Rute B Beltrao Martins', avec_pro_id: '1061778', role: 'other', active: true },
  { id: 'pro-iguatemi-ruth-do-nascimento-abade', name: 'Ruth Do Nascimento Abade', avec_pro_id: '913090', role: 'other', active: true },
  { id: 'pro-iguatemi-ryan-pablo-da-silva-pereira', name: 'Ryan Pablo Da Silva Pereira', avec_pro_id: '1067045', role: 'other', active: true },
  { id: 'pro-iguatemi-sabrina-praxedes-alves-dos-santos-marketing', name: 'Sabrina Praxedes Alves Dos Santos (marketing)', avec_pro_id: '1016753', role: 'other', active: true },
  { id: 'pro-iguatemi-salao', name: 'Salao', avec_pro_id: '912683', role: 'other', active: true },
  { id: 'pro-iguatemi-samanta-uiara-barbosa-silva', name: 'Samanta Uiara Barbosa Silva', avec_pro_id: '918748', role: 'other', active: true },
  { id: 'pro-iguatemi-sandra-novaes-nascimento-dos-santos', name: 'Sandra Novaes Nascimento Dos Santos', avec_pro_id: '913290', role: 'other', active: true },
  { id: 'pro-iguatemi-sandro-dos-santos', name: 'Sandro Dos Santos', avec_pro_id: '1032014', role: 'hairstylist', active: true },
  { id: 'pro-iguatemi-sara-martins-ramos', name: 'Sara Martins Ramos', avec_pro_id: '1003670', role: 'other', active: true },
  { id: 'pro-iguatemi-shirley-batista-ribeiro', name: 'Shirley Batista Ribeiro', avec_pro_id: '995817', role: 'other', active: true },
  { id: 'pro-iguatemi-sidney-mauro-silva-canoto-da-cruz', name: 'Sidney Mauro Silva Canoto Da Cruz', avec_pro_id: '1035430', role: 'other', active: true },
  { id: 'pro-iguatemi-silvana-ferreira-guedes-dos-santos', name: 'Silvana Ferreira Guedes Dos Santos', avec_pro_id: '1121841', role: 'other', active: true },
  { id: 'pro-iguatemi-sinobilino-de-oliveira-filho', name: 'Sinobilino De Oliveira Filho', avec_pro_id: '982923', role: 'other', active: true },
  { id: 'pro-iguatemi-solange-soares-de-souza', name: 'Solange Soares De Souza', avec_pro_id: '1113720', role: 'other', active: true },
  { id: 'pro-iguatemi-sonia-lemos-lessa', name: 'Sonia Lemos Lessa', avec_pro_id: '913250', role: 'hairstylist', active: true },
  { id: 'pro-iguatemi-stefhani-fonseca-garcia', name: 'Stefhani Fonseca Garcia', avec_pro_id: '1085356', role: 'other', active: true },
  { id: 'pro-iguatemi-tainara-silva-dos-santos', name: 'Tainara Silva Dos Santos', avec_pro_id: '1082554', role: 'other', active: true },
  { id: 'pro-iguatemi-tallichan-larissa-vieira-pontes', name: 'Tallichan Larissa Vieira Pontes', avec_pro_id: '995474', role: 'other', active: true },
  { id: 'pro-iguatemi-tamires-marques-de-oliveira-da-costa', name: 'Tamires Marques De Oliveira Da Costa', avec_pro_id: '913025', role: 'hairstylist', active: true },
  { id: 'pro-iguatemi-tatiana-cristina-dos-santos-moura', name: 'Tatiana Cristina Dos Santos Moura', avec_pro_id: '913027', role: 'other', active: true },
  { id: 'pro-iguatemi-tatiane-rodrigues-gomes-barroso', name: 'Tatiane Rodrigues Gomes Barroso', avec_pro_id: '1112439', role: 'other', active: true },
  { id: 'pro-iguatemi-tayna-de-souza-oliveira-almeida', name: 'Tayna De Souza Oliveira Almeida', avec_pro_id: '1110405', role: 'other', active: true },
  { id: 'pro-iguatemi-terminal-salao-baru', name: 'Terminal Salão (baru)', avec_pro_id: '919189', role: 'other', active: true },
  { id: 'pro-iguatemi-thalita-gabrielle-balber-ribeiro', name: 'Thalita Gabrielle Balber Ribeiro', avec_pro_id: '935016', role: 'other', active: true },
  { id: 'pro-iguatemi-thiago-silva-de-jesus', name: 'Thiago Silva De Jesus', avec_pro_id: '921533', role: 'other', active: true },
  { id: 'pro-iguatemi-tiago-bensi', name: 'Tiago Bensi', avec_pro_id: '1051792', role: 'other', active: true },
  { id: 'pro-iguatemi-tiago-matsumoto-castellani', name: 'Tiago Matsumoto Castellani', avec_pro_id: '976984', role: 'other', active: true },
  { id: 'pro-iguatemi-vanessa-lopes-dos-santos', name: 'Vanessa Lopes Dos Santos', avec_pro_id: '1021168', role: 'other', active: true },
  { id: 'pro-iguatemi-victor-augusto-marins-da-silva', name: 'Victor Augusto Marins Da Silva', avec_pro_id: '996215', role: 'hairstylist', active: true },
  { id: 'pro-iguatemi-vilma-araujo-da-silva', name: 'Vilma Araujo Da Silva', avec_pro_id: '918224', role: 'other', active: true },
  { id: 'pro-iguatemi-virginia-bernardo-de-melo', name: 'Virginia Bernardo De Melo', avec_pro_id: '913240', role: 'other', active: true },
  { id: 'pro-iguatemi-vitor-hugo-souza-bueno', name: 'Vitor Hugo Souza Bueno', avec_pro_id: '944590', role: 'other', active: true },
  { id: 'pro-iguatemi-vitor-moreira-de-alvarenga-morais', name: 'Vitor Moreira De Alvarenga Morais', avec_pro_id: '913232', role: 'hairstylist', active: true },
  { id: 'pro-iguatemi-vitor-santos-lopes', name: 'Vitor Santos Lopes', avec_pro_id: '919624', role: 'hairstylist', active: true },
  { id: 'pro-iguatemi-vitoria-carolina-farias-lavrador', name: 'Vitoria Carolina Farias Lavrador', avec_pro_id: '1020535', role: 'other', active: true },
  { id: 'pro-iguatemi-vivian-lazaro-rocha', name: 'Vivian Lazaro Rocha', avec_pro_id: '965197', role: 'other', active: true },
  { id: 'pro-iguatemi-viviana-inacia-vieira', name: 'Viviana Inacia Vieira', avec_pro_id: '913237', role: 'other', active: true },
  { id: 'pro-iguatemi-viviane-de-souza-moreno', name: 'Viviane De Souza Moreno', avec_pro_id: '918226', role: 'other', active: true },
  { id: 'pro-iguatemi-walter-junior', name: 'Walter Junior', avec_pro_id: '1110998', role: 'other', active: true },
  { id: 'pro-iguatemi-walter-martinho-leal-filho-cabeleireiro', name: 'Walter Martinho Leal Filho Cabeleireiro', avec_pro_id: '965679', role: 'hairstylist', active: true },
  { id: 'pro-iguatemi-wesley-santos-de-moura', name: 'Wesley Santos De Moura', avec_pro_id: '913210', role: 'other', active: true },
  { id: 'pro-iguatemi-willian-axl-troyano', name: 'Willian Axl Troyano', avec_pro_id: '1114611', role: 'other', active: true },
  { id: 'pro-iguatemi-willian-oliveira-da-silva', name: 'Willian Oliveira Da Silva', avec_pro_id: '1115036', role: 'other', active: true },
  { id: 'pro-iguatemi-willyan-thiago-franco-sass', name: 'Willyan Thiago Franco Sass', avec_pro_id: '913287', role: 'other', active: true },
  { id: 'pro-iguatemi-yara-paiva-ferreira', name: 'Yara Paiva Ferreira', avec_pro_id: '1021748', role: 'other', active: true },
  { id: 'pro-iguatemi-yonara-luiza-cristina-mariano', name: 'Yonara Luiza Cristina Mariano', avec_pro_id: '956840', role: 'other', active: true },
]
